# steps:
#   - name: gcr.io/cloud-builders/docker
#     args:
#       - build
#       - '-t'
#       - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
#       - .
#   - name: gcr.io/cloud-builders/docker
#     args:
#       - push
#       - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
#   - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#     args:
#       - run
#       - deploy
#       - $_SERVICE_NAME
#       - '--image'
#       - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
#       - '--region'
#       - $_DEPLOY_REGION
#       - '--platform'
#       - $_PLATFORM
#     entrypoint: gcloud
# timeout: 1200s
# images:
#   - '$_AR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - $_SERVICE_NAME
    - '--image'
    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
    - '--region'
    - $_DEPLOY_REGION
  images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'